version: '2.3'
networks:
    ttm4200_net:
        enable_ipv6: true
        ipam:
            config:
                #configure subnet range (both IPv6 and IPv4)
                ========== FILL IN HERE ==========
services:
    node:
        build: ./node-server/
        container_name: node-server
        hostname: node-server
        cap_add:
            - NET_ADMIN
        ports:
            #map port 8080 on the host machine to port 8080 in the container
            ========== FILL IN HERE ==========
        networks:
            ttm4200_net:
                #assign the node service an IPv6 address and IPv4 address
                ========= FILL IN HERE =========d
    client:
        build: ./client/
        container_name: client
        hostname: client
        user: root
        tty: true
        stdin_open: true
        cap_add:
            - NET_ADMIN
        volumes:
        - ./client/:/home
        networks:
            ttm4200_net:
                #assign the client service an IPv6 address and IPv4 address
                ========== FILL IN HERE ========